method_class : VQE
simulation_object: Electronic

hamiltonian_params:
    file: h2.xyz
    mapping: jordan_wigner
    charge: 
    mult:
    basis:
    method:
    pauli_string: [[ZZI, 0.1]]
    spin: 1

ansatz_params:
    repetitions: 1
    electrons: 2
    base: default.qubit
    backend: 
    interface: autograd
    shots: 1000.0
    token: 

minimizate_method: Gradient
minimizate_method_params:
    type: "COBYLA"
    maxiter: 200
    tol: 0.000001
    step_theta: 0.45
    step_x: 0.8

observable_params:
    observable: Density charge
    file: OptimumVQEElectronic.csv