method_class : VQE
simulation_object: Spin

hamiltonian_params:
    file: h2.xyz
    mapping: jordan_wigner
    charge: 
    mult:
    basis:
    method:
    pauli_string: [[ZZI, 1], [IZZ, 1]]
    spin: 0.5

ansatz_params:
    repetitions: 1
    electrons: 2
    base: default.qubit
    backend: 
    interface: autograd
    shots: 1000.0
    token: 

minimizate_method: Scipy
minimizate_method_params:
    type: SLSQP
    maxiter: 100
    tol: 0.000001
    step_theta: 1.0
    step_x: 0.8

observable_params:
    observable: Magnetization GS
    file: OptimumVQESpin.csv
    lim_sup: 0.0
    lim_inf: 100

    number_points: 101
    delta: 0.2