name: Publish Python 🐍 distributions 📦 to PyPI
on:
  push:
    tags:
     - '*'

permissions:
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        
    - name: Extract tag name
      id: tag
      run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)
      
    - name: Update pyproject.toml
      run: |
        sed -i "s/version = .*/version = \"${{ steps.tag.outputs.TAG_NAME }}\"/" pyproject.toml
        cat pyproject.toml
          
    - name: Build package
      run: python -m build

    - name: Upload package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
